### ISSUE TITLE
Seems like only content under `content/post` is rendered?

### ISSUE THREAD

**Issue by thedch** [azmelanar/hugo-theme-pixyll#37]
Is there documentation on how to switch that to `posts`? (or inform the user that the `posts` directory is getting ignored?

**Comment by thedch** [comment]
In the example site `config.toml` I tried changing 

```
[params]
  mainSections = ["post"]
```

to 

```
[params]
  mainSections = ["posts"]
```

but that does not seem to do anything

**Comment by pchng** [comment]
There appear to be a few things hard-coding the use of `post` as the type rather than `posts`:

1. In `index.html` if you do not have `.Site.Params.paginate` set, then it defaults to rendering only those of type `post`. (Otherwise if you have `paginate = true` set under `[params]` then the `mainSections` setting is respected.
2. `index.html` is using `.Render "summary"`, and this view only exists in `layouts/post/summary.html`

So you would probably want to address at least these two things in order to be able to change from `post` to whatever just by editing `config.toml`.

**Comment by pchng** [comment]
Also the Hugo documentation seems to be a little ambiguous regarding types and how they are automatically created vs. how they are styled in a theme. (I'm just trying to learn Hugo, so please excuse me if anything is incorrect)

For example, [here](https://gohugo.io/content-management/types/) they say:

> Therefore a new file created at content/posts/new-post.md will automatically be assigned the type posts.

However, on the same page they also say:

> Create a directory with the name of the type in /layouts. For creating these custom layouts, type is always singular; e.g., events => event and posts => post.

This probably leads to the inconsistency here as many people will be creating content automatically typed as `posts` (plural) (unless overridden) while also the recommendation is to name the layout directory as `post` (singular), leading to the inconsistency seen here.
